replicaCount: 1

image:
  repository: 713608733208.dkr.ecr.us-west-2.amazonaws.com/microservices
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000

resources: {}

